
name: Build and deploy Node.js app to Azure Web App - tospotdev

on:
  push:
    branches:
      - DEV
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # You can use a more stable LTS version if it suits your project

      - name: npm install, build, and test
        run: |
          npm install
          npm run build -- --configuration=dev

      - name: Compress deployment package
        run: |
          tar -czvf node-app.tar.gz *
        working-directory: ./path/to/deployment/package

      - name: Upload compressed artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: path/to/deployment/package/node-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'tospotdev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9BBB33D3CA8147E4AD13018411C4ED39 }}
          package: ${{ runner.workspace }}/node-app.tar.gz