# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: DEPLOYMENT - DEV - SPOTUI

on:
  push:
    branches:
      - DEV
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install -g npm-cli-login
          npm config set "@bryntum:registry=https://npm.bryntum.com"
          npm-cli-login -r https://npm.bryntum.com -u 'prakhar.agrawal..takeda.com' -p trial -e prakhar.agrawal@takeda.com
          npm install
          npm run build -- --configuration=dev

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tospotdev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1826921C44EA4653BACC2D8B31EB315E }}
          package: './dist/fuse'
