# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: DEPLOYMENT- PROD- SPOTUI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm install -g npm-cli-login
          npm config set "@bryntum:registry=https://npm.bryntum.com"
          npm-cli-login -r https://npm.bryntum.com -u 'prakhar.agrawal..takeda.com' -p trial -e prakhar.agrawal@takeda.com
          npm install
          npm run build -- --configuration=prod

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'tospot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E053E82EE1384D76963D74D75BF24282 }}
          package: './dist/fuse'
